--  Generate SQL 
--  Version:                   	V7R1M0 100423 
--  Generated on:              	09/02/16 15:19:13 
--  Relational Database:       	SWIFTDB 
--  Standards Option:          	DB2 for i 
SET PATH *LIBL ; 
  
CREATE FUNCTION HRTEST/TIMEOFF_GET_UNAPPROVED_HOURS ( 
	IN_EMPLOYEE_NUMBER VARCHAR(9) , 
	IN_CATEGORY VARCHAR(1) ) 
	RETURNS TABLE ( 
	UNAPPROVED DECIMAL(9, 2) )   
	LANGUAGE SQL 
	SPECIFIC HRTEST/TOGTUHRS 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	NO EXTERNAL ACTION 
	ALLOW PARALLEL 
	CARDINALITY 1 
	CONCURRENT ACCESS RESOLUTION USE CURRENTLY COMMITTED 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DLYPRP = *NO , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN RETURN WITH A ( UNAPPROVED ) AS ( SELECT COALESCE ( SUM ( E . REQUESTED_HOURS ) , 0 ) FROM TIMEOFF_REQUEST_ENTRIES E JOIN TIMEOFF_REQUESTS R ON E . REQUEST_ID = R . REQUEST_ID WHERE R . EMPLOYEE_NUMBER = REFACTOR_EMPLOYEE_ID ( IN_EMPLOYEE_NUMBER ) 
AND 
E . REQUEST_CODE = IN_CATEGORY AND R . REQUEST_STATUS = 'P' AND E . IS_DELETED = '0' ) SELECT A . UNAPPROVED FROM A ; END  ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC FUNCTION HRTEST/TOGTUHRS 
TO ALDONCMS ; 
  
GRANT EXECUTE   
ON SPECIFIC FUNCTION HRTEST/TOGTUHRS 
TO PUBLIC ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC FUNCTION HRTEST/TOGTUHRS 
TO S2KOBJOWNR ; 
  
