BEGIN

RETURN

WITH

A ( UNAPPROVED )
AS (
	SELECT COALESCE ( SUM ( E . REQUESTED_HOURS ) , 0 )
	FROM TIMEOFF_REQUEST_ENTRIES E
	JOIN TIMEOFF_REQUESTS R ON E . REQUEST_ID = R . REQUEST_ID
	WHERE R . EMPLOYEE_NUMBER = REFACTOR_EMPLOYEE_ID ( IN_EMPLOYEE_NUMBER ) AND
	E . REQUEST_CODE = IN_CATEGORY AND
	R . REQUEST_STATUS = 'P' AND
	E . IS_DELETED = '0'
)

SELECT A . UNAPPROVED
FROM A ;;

END ;;