BEGIN:VEVENT
UID:<?php echo $this->formatUID; ?>swifttrans.com
DTSTART;TZID=<?php echo $this->timeZone; ?>:<?php echo $this->startDate; ?>T<?php echo $this->startTime; ?>00
DTEND;TZID=<?php echo $this->timeZone; ?>:<?php echo $this->endDate; ?>T<?php echo $this->endTime; ?>00
DTSTAMP:<?php echo $this->dtStamp; ?>
SUMMARY:<?php echo $this->subject; ?>
LOCATION:
DESCRIPTION:<?php echo $this->descriptionString; ?>
STATUS:CONFIRMED
X-MICROSOFT-CDO-BUSYSTATUS:FREE
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-CDO-INTENDEDSTATUS:FREE
X-MICROSOFT-CDO-ALLDAYEVENT:TRUE
FBTYPE:FREE
ORGANIZER;CN=<?php echo $this->fromName; ?>:mailto:<?php echo $this->fromEmail; ?>
<?php echo $this->participantsText; ?>
END:VEVENT