--  Generate SQL 
--  Version:                   	V7R1M0 100423 
--  Generated on:              	04/14/16 11:05:21 
--  Relational Database:       	SWIFTDB 
--  Standards Option:          	DB2 for i 
CREATE TABLE SAWIK/TIMEOFF_REQUEST_EMPLOYEE_PROXIES FOR SYSTEM NAME TOEMPPRX ( 
	EMPLOYEE_NUMBER FOR COLUMN EMPNUM     VARCHAR(9) CCSID 37 DEFAULT NULL , 
	PROXY_EMPLOYEE_NUMBER FOR COLUMN PRXEMPNUM  VARCHAR(9) CCSID 37 DEFAULT NULL )   
	  
	RCDFMT TOEMPPRX   ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON SAWIK/TIMEOFF_REQUEST_EMPLOYEE_PROXIES TO QPGMR WITH GRANT OPTION ;