--  Generate SQL 
--  Version:                   	V7R1M0 100423 
--  Generated on:              	09/02/16 15:12:17 
--  Relational Database:       	SWIFTDB 
--  Standards Option:          	DB2 for i 
CREATE TABLE HRTEST/TIMEOFF_REQUEST_LOG FOR SYSTEM NAME TOREQLOG ( 
	REQUEST_ID FOR COLUMN REQUESTID  DECIMAL(13, 0) DEFAULT NULL , 
	EMPLOYEE_NUMBER FOR COLUMN EMPNUM     VARCHAR(9) CCSID 37 DEFAULT NULL , 
	"COMMENT" VARCHAR(625) CCSID 37 DEFAULT NULL , 
	CREATE_TIMESTAMP FOR COLUMN CRTTS      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , 
	COMMENT_TYPE FOR COLUMN COMMENTTYP CHAR(1) CCSID 37 NOT NULL DEFAULT 'S' )   
	  
	RCDFMT TOREQLOG   ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON HRTEST/TIMEOFF_REQUEST_LOG TO ALDONCMS WITH GRANT OPTION ; 
  
GRANT SELECT   
ON HRTEST/TIMEOFF_REQUEST_LOG TO PUBLIC ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON HRTEST/TIMEOFF_REQUEST_LOG TO S2KOBJOWNR WITH GRANT OPTION ; 
  
