--  Generate SQL 
--  Version:                   	V7R1M0 100423 
--  Generated on:              	09/02/16 15:09:53 
--  Relational Database:       	SWIFTDB 
--  Standards Option:          	DB2 for i 
CREATE TABLE HRTEST/TIMEOFF_REQUEST_CODES FOR SYSTEM NAME TOREQCODES ( 
	REQUEST_CODE FOR COLUMN REQCODE    VARCHAR(1) CCSID 37 NOT NULL DEFAULT '' , 
	DESCRIPTION FOR COLUMN REQCDDESC  VARCHAR(50) CCSID 37 NOT NULL DEFAULT '' , 
	CALENDAR_DAY_CLASS FOR COLUMN CALDAYCL   VARCHAR(35) CCSID 37 DEFAULT NULL )   
	  
	RCDFMT TOREQCODE1 ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON HRTEST/TIMEOFF_REQUEST_CODES TO ALDONCMS WITH GRANT OPTION ; 
  
GRANT SELECT   
ON HRTEST/TIMEOFF_REQUEST_CODES TO PUBLIC ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON HRTEST/TIMEOFF_REQUEST_CODES TO S2KOBJOWNR WITH GRANT OPTION ; 
  
