--  Generate SQL 
--  Version:                   	V7R1M0 100423 
--  Generated on:              	09/02/16 15:14:29 
--  Relational Database:       	SWIFTDB 
--  Standards Option:          	DB2 for i 
CREATE TABLE HRTEST/TIMEOFF_REQUESTS FOR SYSTEM NAME TOREQUESTS ( 
	REQUEST_ID FOR COLUMN REQUESTID  INTEGER GENERATED ALWAYS AS IDENTITY ( 
	START WITH 100000 INCREMENT BY 1 
	NO MINVALUE MAXVALUE 2147483647 
	NO CYCLE NO ORDER 
	CACHE 20 ) 
	, 
	EMPLOYEE_NUMBER FOR COLUMN EMPNUM     VARCHAR(9) CCSID 37 NOT NULL DEFAULT '' , 
	REQUEST_STATUS FOR COLUMN REQSTAT    VARCHAR(1) CCSID 37 NOT NULL DEFAULT '' , 
	CREATE_USER FOR COLUMN CRTEMPID   VARCHAR(9) CCSID 37 NOT NULL DEFAULT '' , 
	CREATE_TIMESTAMP FOR COLUMN CRTTS      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , 
	UPDATE_TIMESTAMP FOR COLUMN UPDTS      TIMESTAMP GENERATED ALWAYS FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP NOT NULL , 
	REQUEST_REASON FOR COLUMN REASON     VARCHAR(500) CCSID 37 DEFAULT NULL , 
	EMPLOYEE_DATA FOR COLUMN EMPDATA    VARCHAR(32000) CCSID 37 DEFAULT NULL )   
	  
	RCDFMT TOREQUEST1 ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON HRTEST/TIMEOFF_REQUESTS TO ALDONCMS WITH GRANT OPTION ; 
  
GRANT SELECT   
ON HRTEST/TIMEOFF_REQUESTS TO PUBLIC ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON HRTEST/TIMEOFF_REQUESTS TO S2KOBJOWNR WITH GRANT OPTION ; 
  
