--  Generate SQL 
--  Version:                   	V7R1M0 100423 
--  Generated on:              	08/31/16 14:19:51 
--  Relational Database:       	SWIFTDB 
--  Standards Option:          	DB2 for i 
CREATE TABLE SAWIK2/TIMEOFF_REQUEST_STATUSES FOR SYSTEM NAME TOSTATUS ( 
	REQUEST_STATUS FOR COLUMN REQSTAT    VARCHAR(1) CCSID 37 NOT NULL DEFAULT '' , 
	DESCRIPTION FOR COLUMN REQDESC    VARCHAR(50) CCSID 37 NOT NULL DEFAULT '' )   
	  
	RCDFMT TOREQCODE1 ; 
  
GRANT DELETE , INSERT , SELECT , UPDATE   
ON SAWIK2/TIMEOFF_REQUEST_STATUSES TO CAREDEV ; 
  
GRANT DELETE , INSERT , SELECT , UPDATE   
ON SAWIK2/TIMEOFF_REQUEST_STATUSES TO CARETEST ; 
  
GRANT DELETE , INSERT , SELECT , UPDATE   
ON SAWIK2/TIMEOFF_REQUEST_STATUSES TO PUBLIC ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON SAWIK2/TIMEOFF_REQUEST_STATUSES TO QPGMR WITH GRANT OPTION ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON SAWIK2/TIMEOFF_REQUEST_STATUSES TO S2KOBJOWNR WITH GRANT OPTION ;
