--  Generate SQL
--  Version:                    V7R1M0 100423
--  Generated on:               09/06/16 10:35:39
--  Relational Database:        SWIFTDB
--  Standards Option:           DB2 for i
CREATE TABLE TIMEOFF_REQUEST_EMAIL_REMINDER FOR SYSTEM NAME TOEMLRMD (
    IDENTITY_ID FOR COLUMN IDENTITYID BIGINT GENERATED ALWAYS AS IDENTITY (
    START WITH 1 INCREMENT BY 1
    NO MINVALUE NO MAXVALUE
    NO CYCLE NO ORDER
    CACHE 20 )
    ,
    EMAIL_SEND VARCHAR(1) ALLOCATE(1) CCSID 37 NOT NULL DEFAULT 'N' ,
    EMAIL_SEND_ON FOR COLUMN EMAIL00001 TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    REQUEST_ID INTEGER NOT NULL DEFAULT 0 )

    RCDFMT TOEMLRMD1  ;

LABEL ON TABLE TIMEOFF_REQUEST_EMAIL_REMINDER
    IS 'Time-Off Email Reminder' ;

LABEL ON COLUMN TIMEOFF_REQUEST_EMAIL_REMINDER
( IDENTITY_ID IS 'Identity ID          ' ) ;

LABEL ON COLUMN TIMEOFF_REQUEST_EMAIL_REMINDER
( IDENTITY_ID TEXT IS 'Identity ID' ) ;

GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE
ON TIMEOFF_REQUEST_EMAIL_REMINDER TO FAECG WITH GRANT OPTION ;
