--  Generate SQL 
--  Version:                   	V7R1M0 100423 
--  Generated on:              	09/02/16 15:14:54 
--  Relational Database:       	SWIFTDB 
--  Standards Option:          	DB2 for i 
CREATE TABLE HRTEST/TIMEOFF_REQUESTS_PAYROLL_ADMINS FOR SYSTEM NAME TOPAYADM ( 
	EMPLOYEE_NUMBER FOR COLUMN EMPNUM     VARCHAR(9) CCSID 37 DEFAULT NULL , 
	STATUS VARCHAR(1) ALLOCATE(1) CCSID 37 NOT NULL DEFAULT '0' , 
	CREATED_BY FOR COLUMN CREATEDBY  VARCHAR(9) CCSID 37 DEFAULT NULL , 
	CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP , 
	MODIFIED TIMESTAMP GENERATED ALWAYS FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP NOT NULL )   
	  
	RCDFMT TOPAYADM   ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON HRTEST/TIMEOFF_REQUESTS_PAYROLL_ADMINS TO ALDONCMS WITH GRANT OPTION ; 
  
GRANT SELECT   
ON HRTEST/TIMEOFF_REQUESTS_PAYROLL_ADMINS TO PUBLIC ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON HRTEST/TIMEOFF_REQUESTS_PAYROLL_ADMINS TO S2KOBJOWNR WITH GRANT OPTION ; 
  
