--  Generate SQL 
--  Version:                   	V7R1M0 100423 
--  Generated on:              	08/31/16 14:16:09 
--  Relational Database:       	SWIFTDB 
--  Standards Option:          	DB2 for i 
CREATE TABLE SAWIK2/TIMEOFF_REQUEST_EMPLOYEE_PROXIES FOR SYSTEM NAME TOEMPPRX ( 
	EMPLOYEE_NUMBER FOR COLUMN EMPNUM     VARCHAR(9) CCSID 37 DEFAULT NULL , 
	PROXY_EMPLOYEE_NUMBER FOR COLUMN PRXEMPNUM  VARCHAR(9) CCSID 37 DEFAULT NULL , 
	STATUS VARCHAR(1) ALLOCATE(1) CCSID 37 DEFAULT '0' )   
	  
	RCDFMT TOEMPPRX   ; 
  
GRANT DELETE , INSERT , SELECT , UPDATE   
ON SAWIK2/TIMEOFF_REQUEST_EMPLOYEE_PROXIES TO PUBLIC ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON SAWIK2/TIMEOFF_REQUEST_EMPLOYEE_PROXIES TO QPGMR WITH GRANT OPTION ;
