--  Generate SQL 
--  Version:                   	V7R1M0 100423 
--  Generated on:              	08/31/16 14:18:57 
--  Relational Database:       	SWIFTDB 
--  Standards Option:          	DB2 for i 
CREATE TABLE SAWIK2/TIMEOFF_REQUEST_LOG FOR SYSTEM NAME TOREQLOG ( 
	REQUEST_ID FOR COLUMN REQUESTID  DECIMAL(13, 0) DEFAULT NULL , 
	EMPLOYEE_NUMBER FOR COLUMN EMPNUM     VARCHAR(9) CCSID 37 DEFAULT NULL , 
	"COMMENT" VARCHAR(625) CCSID 37 DEFAULT NULL , 
	CREATE_TIMESTAMP FOR COLUMN CRTTS      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , 
	COMMENT_TYPE FOR COLUMN COMMENTTYP CHAR(1) CCSID 37 NOT NULL DEFAULT 'S' )   
	  
	RCDFMT TOREQLOG   ; 
  
LABEL ON COLUMN SAWIK2/TIMEOFF_REQUEST_LOG 
( COMMENT_TYPE TEXT IS 'Comment type: S=System, P=Payroll; Default=S' ) ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON SAWIK2/TIMEOFF_REQUEST_LOG TO QPGMR WITH GRANT OPTION ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON SAWIK2/TIMEOFF_REQUEST_LOG TO SAWIK WITH GRANT OPTION ;
