--  Generate SQL 
--  Version:                   	V7R1M0 100423 
--  Generated on:              	09/02/16 15:11:03 
--  Relational Database:       	SWIFTDB 
--  Standards Option:          	DB2 for i 
CREATE TABLE HRTEST/TIMEOFF_REQUEST_EMPLOYEE_SCHEDULES FOR SYSTEM NAME TOEMPSCH ( 
	EMPLOYEE_NUMBER FOR COLUMN EMPNUM     VARCHAR(9) CCSID 37 DEFAULT NULL , 
	SCHEDULE_MON FOR COLUMN SCHMON     DECIMAL(7, 2) DEFAULT NULL , 
	SCHEDULE_TUE FOR COLUMN SCHTUE     DECIMAL(7, 2) DEFAULT NULL , 
	SCHEDULE_WED FOR COLUMN SCHWED     DECIMAL(7, 2) DEFAULT NULL , 
	SCHEDULE_THU FOR COLUMN SCHTHU     DECIMAL(7, 2) DEFAULT NULL , 
	SCHEDULE_FRI FOR COLUMN SCHFRI     DECIMAL(7, 2) DEFAULT NULL , 
	SCHEDULE_SAT FOR COLUMN SCHSAT     DECIMAL(7, 2) DEFAULT NULL , 
	SCHEDULE_SUN FOR COLUMN SCHSUN     DECIMAL(7, 2) DEFAULT NULL , 
	SEND_CAL_INV_ME FOR COLUMN CALINVME   CHAR(1) CCSID 37 NOT NULL DEFAULT '1' , 
	SEND_CAL_INV_RPT FOR COLUMN CALINVRPT  CHAR(1) CCSID 37 NOT NULL DEFAULT '1' , 
	CONSTRAINT HRTEST/Q_HRTEST_TOEMPSCH_EMPNUM_00001 PRIMARY KEY( EMPLOYEE_NUMBER ) )   
	  
	RCDFMT TOEMPSCH   ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON HRTEST/TIMEOFF_REQUEST_EMPLOYEE_SCHEDULES TO ALDONCMS WITH GRANT OPTION ; 
  
GRANT SELECT   
ON HRTEST/TIMEOFF_REQUEST_EMPLOYEE_SCHEDULES TO PUBLIC ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON HRTEST/TIMEOFF_REQUEST_EMPLOYEE_SCHEDULES TO S2KOBJOWNR WITH GRANT OPTION ; 
  
