CREATE TABLE SAWIK2/TIMEOFF_REQUESTS_PAYROLL_ASSISTANTS FOR SYSTEM NAME TOPAYAST ( 
	EMPLOYEE_NUMBER FOR COLUMN EMPNUM     VARCHAR(9) CCSID 37 DEFAULT NULL , 
	STATUS VARCHAR(1) ALLOCATE(1) CCSID 37 NOT NULL DEFAULT '0' )   
	  
	RCDFMT TOPAYAST   ; 
  
ALTER TABLE SAWIK2/TIMEOFF_REQUESTS_PAYROLL_ASSISTANTS 
	ADD CONSTRAINT SAWIK2/Q_SAWIK2_TOPAYAST_EMPNUM_00001 
	UNIQUE( EMPLOYEE_NUMBER ) ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON SAWIK2/TIMEOFF_REQUESTS_PAYROLL_ASSISTANTS TO QPGMR WITH GRANT OPTION ;