--  Generate SQL 
--  Version:                   	V7R1M0 100423 
--  Generated on:              	08/31/16 14:16:54 
--  Relational Database:       	SWIFTDB 
--  Standards Option:          	DB2 for i 
CREATE TABLE SAWIK2/TIMEOFF_REQUEST_ENTRIES FOR SYSTEM NAME TOENTRY ( 
	ENTRY_ID FOR COLUMN ENTRYID    INTEGER GENERATED ALWAYS AS IDENTITY ( 
	START WITH 500 INCREMENT BY 1 
	MINVALUE 500 NO MAXVALUE 
	NO CYCLE NO ORDER 
	CACHE 20 ) 
	, 
	REQUEST_ID FOR COLUMN REQUESTID  INTEGER NOT NULL DEFAULT 0 , 
	REQUEST_DATE FOR COLUMN REQUESTDT  DATE NOT NULL DEFAULT CURRENT_DATE , 
	REQUESTED_HOURS FOR COLUMN REQUESTHRS DECIMAL(4, 2) NOT NULL DEFAULT 0 , 
	REQUEST_CODE FOR COLUMN REQCODE    VARCHAR(1) CCSID 37 NOT NULL DEFAULT '' , 
	WRITTMP CHAR(1) CCSID 37 NOT NULL DEFAULT 'N' , 
	LOCKED CHAR(1) CCSID 37 NOT NULL DEFAULT 'N' , 
	REQUEST_DAY_OF_WEEK FOR COLUMN REQDOW     VARCHAR(3) CCSID 37 DEFAULT NULL , 
	IS_DELETED FOR COLUMN ISDELETED  VARCHAR(1) ALLOCATE(1) CCSID 37 NOT NULL DEFAULT '0' )   
	  
	RCDFMT TOREQCODE1 ; 
  
GRANT DELETE , INSERT , SELECT , UPDATE   
ON SAWIK2/TIMEOFF_REQUEST_ENTRIES TO PUBLIC ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON SAWIK2/TIMEOFF_REQUEST_ENTRIES TO QPGMR WITH GRANT OPTION ;
