--  Generate SQL 
--  Version:                   	V7R1M0 100423 
--  Generated on:              	09/02/16 15:15:24 
--  Relational Database:       	SWIFTDB 
--  Standards Option:          	DB2 for i 
CREATE TABLE HRTEST/TIMEOFF_REQUESTS_PAYROLL_ASSISTANTS FOR SYSTEM NAME TOPAYAST ( 
	EMPLOYEE_NUMBER FOR COLUMN EMPNUM     VARCHAR(9) CCSID 37 DEFAULT NULL , 
	STATUS VARCHAR(1) ALLOCATE(1) CCSID 37 NOT NULL DEFAULT '0' , 
	CREATED_BY FOR COLUMN CREATEDBY  VARCHAR(9) CCSID 37 DEFAULT NULL , 
	CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP , 
	MODIFIED TIMESTAMP GENERATED ALWAYS FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP NOT NULL )   
	  
	RCDFMT TOPAYAST   ; 
  
ALTER TABLE HRTEST/TIMEOFF_REQUESTS_PAYROLL_ASSISTANTS 
	ADD CONSTRAINT HRTEST/Q_HRTEST_TOPAYAST_EMPNUM_00001 
	UNIQUE( EMPLOYEE_NUMBER ) ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON HRTEST/TIMEOFF_REQUESTS_PAYROLL_ASSISTANTS TO ALDONCMS WITH GRANT OPTION ; 
  
GRANT SELECT   
ON HRTEST/TIMEOFF_REQUESTS_PAYROLL_ASSISTANTS TO PUBLIC ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON HRTEST/TIMEOFF_REQUESTS_PAYROLL_ASSISTANTS TO S2KOBJOWNR WITH GRANT OPTION ; 
  
