--  Generate SQL 
--  Version:                   	V7R1M0 100423 
--  Generated on:              	09/02/16 15:11:51 
--  Relational Database:       	SWIFTDB 
--  Standards Option:          	DB2 for i 
CREATE TABLE HRTEST/TIMEOFF_REQUEST_ENTRIES_ARCHIVE FOR SYSTEM NAME TOREQARC ( 
	ENTRY_ARCHIVE_ID FOR COLUMN ENTARCID   INTEGER GENERATED ALWAYS AS IDENTITY ( 
	START WITH 1 INCREMENT BY 1 
	NO MINVALUE NO MAXVALUE 
	NO CYCLE NO ORDER 
	CACHE 20 ) 
	, 
	REQUEST_ID FOR COLUMN REQUESTID  INTEGER NOT NULL , 
	ENTRY_ID FOR COLUMN ENTRYID    INTEGER NOT NULL , 
	REQUEST_DATA FOR COLUMN REQDATA    VARCHAR(32000) CCSID 37 DEFAULT NULL )   
	  
	RCDFMT TOREQARC   ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON HRTEST/TIMEOFF_REQUEST_ENTRIES_ARCHIVE TO ALDONCMS WITH GRANT OPTION ; 
  
GRANT SELECT   
ON HRTEST/TIMEOFF_REQUEST_ENTRIES_ARCHIVE TO PUBLIC ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON HRTEST/TIMEOFF_REQUEST_ENTRIES_ARCHIVE TO S2KOBJOWNR WITH GRANT OPTION ; 
  
