--  Generate SQL 
--  Version:                   	V7R1M0 100423 
--  Generated on:              	09/02/16 15:13:34 
--  Relational Database:       	SWIFTDB 
--  Standards Option:          	DB2 for i 
CREATE TABLE HRTEST/TIMEOFF_REQUEST_STATUSES FOR SYSTEM NAME TOSTATUS ( 
	REQUEST_STATUS FOR COLUMN REQSTAT    VARCHAR(1) CCSID 37 NOT NULL DEFAULT '' , 
	DESCRIPTION FOR COLUMN REQDESC    VARCHAR(50) CCSID 37 NOT NULL DEFAULT '' )   
	  
	RCDFMT TOREQCODE1 ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON HRTEST/TIMEOFF_REQUEST_STATUSES TO ALDONCMS WITH GRANT OPTION ; 
  
GRANT SELECT   
ON HRTEST/TIMEOFF_REQUEST_STATUSES TO PUBLIC ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON HRTEST/TIMEOFF_REQUEST_STATUSES TO S2KOBJOWNR WITH GRANT OPTION ; 
  
