<h4><?php echo $payrollViewName; ?> Queue</h4>

<br />

<?php if($isLoggedInUserPayroll==="Y") { ?>

<table id="payroll-queue-<?php echo $this->payrollView; ?>" class="display" style="width:100%;">
    <thead>
        <tr>
            <th>Employee</th>
            <th>Approver queue</th>
            <th>Request Status</th>
            <th>Hours Requested</th>
            <th>Request Reason</th>
            <th>First Day<br />Requested</th>
            <th>Actions</th>
        </tr>
    </thead>
</table>

<?php } else { ?>

<div class="alert alert-danger" role="alert">
	<span class="glyphicon glyphicon-warning-sign pull-left" aria-hidden="true"></span>&nbsp;&nbsp;
	<strong>You do not have access to this page.</strong>
</div>

<?php } ?>

<script type="text/javascript" src="<?php echo $this->basePath( 'js/datatables/datatables.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath( 'js/request/timeOffPayrollQueueHandler.js'); ?>"></script>