<div class="alert alert-warning" role="alert">
    <div class="glyphicon glyphicon-exclamation-sign"></div>
    <div>
        Are you sure you want to delete
        '<?php echo $this->escapeHtml($post->title); ?>' by
        '<?php echo $this->escapeHtml($post->bodytext); ?>'?
    </div>
</div>

<form action="<?php echo $this->url('post/delete', array(), true) ?>" method="post">
    <input type="submit" class="btn btn-form-primary" name="delete_confirmation" value="yes">
    <input type="submit" class="btn btn-form-primary" name="delete_confirmation" value="no">
</form>
