<h1>WriteController::editAction()</h1>
<?php
$form = $this->form;
$form->setAttribute('method', 'POST');
$form->setAttribute('action', $this->url('blog/edit', array(), true));
$form->prepare();
$form->get('submit')->setValue('Update Post');
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
?>

<!--
<div class="row rowMinHeight visible-lg">
    <div class="col-lg-1">

    </div>
    <div class="col-lg-2">
        <label for="new_document_type">Abbr.</label>
    </div>
    <div class="col-lg-6">
        <label for="new_document_type">Description</label>
    </div>
    <div class="col-lg-1 text-center">
        <label for="new_document_type"># Docs</label>
    </div>
    <div class="col-lg-1 text-center">
        <label for="new_document_type"># Active</label>
    </div>
    <div class="col-lg-1">

    </div>
</div>
-->

