<h1>Blog</h1>

<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>TITLE</th>
            <th>TEXT</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->posts as $post) { ?>
            <tr>
                <td><?php echo $post->getId(); ?></td>
                <td><?php echo $post->getTitle(); ?></td>
                <td><?php echo $post->getText(); ?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>
