<h3>View Post ID <?php echo $this->post->getId(); ?></h3>

<div class="row rowMinHeight">
    <div class="col-xs-2 col-sm-2 col-md-2 col-lg-3">

    </div>
    <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
        <strong>Title</strong>
    </div>
    <div class="col-xs-7 col-sm-7 col-md-7 col-lg-6">
        <?php echo $this->escapeHtml($this->post->getTitle());?>
    </div>
</div>

<div class="row rowMinHeight">
    <div class="col-xs-2 col-sm-2 col-md-2 col-lg-3">

    </div>
    <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
        <strong>Text</strong>
    </div>
    <div class="col-xs-7 col-sm-7 col-md-7 col-lg-6">
        <?php echo $this->escapeHtml($this->post->getText());?>
        <br /><br />
        <a href="<?php echo $this->basepath(); ?>/blog/edit/<?php echo $this->post->getId(); ?>"><button type="button" class="btn btn-form-primary">Edit</button></a><br />
        <a href="<?php echo $this->url('blog', ['action' => 'edit', 'id' => $this->post->getId()]); ?>"><button type="button" class="btn btn-form-primary">Edit</button></a><br />
    </div>
</div>

<a href="<?php echo $this->url('blog'); ?>"><button type="button" class="btn btn-form-primary">View Posts</button></a>
