<strong>Employee Time Off Hours for <?php echo ucwords($employeeData->FIRST_NAME); ?> <?php echo ucwords($employeeData->LAST_NAME); ?></strong>
<br />
<br />
<br />

<div class="timeOffCategoryLeft timeOffPTO">
	&nbsp;<br />&nbsp;
</div>
<div class="timeOffCategory" data-category="timeOffPTO">
	PTO<br />
	<span class="hours"><?php echo number_format($employeeData->PTO_AVAILABLE, 2); ?> hr</span>
</div>

<div class="timeOffCategoryLeft timeOffFloat">
	&nbsp;<br />&nbsp;
</div>
<div class="timeOffCategory" data-category="timeOffFloat">
	Float<br />
	<span class="hours"><?php echo number_format($employeeData->FLOAT_AVAILABLE, 2); ?> hr</span>
</div>

<div class="timeOffCategoryLeft timeOffSick">
	&nbsp;<br />
	&nbsp;
</div>
<div class="timeOffCategory" data-category="timeOffSick">
	Sick<br />
	<span class="hours"><?php echo number_format($employeeData->SICK_AVAILABLE, 2); ?> hr</span>
</div>

<br /><br /><br />

<br style="clear:both;" />

<div style="width:33%;padding-right:10px;float:left;text-align:center;">
	<strong>December 2015</strong><br /><br />
	<?php echo $calendar1Html; ?>
</div>
<div style="width:33%;padding-right:10px;float:left;text-align:center;">
	<strong>January 2016</strong><br /><br />
	<?php echo $calendar2Html; ?>
</div>
<div style="width:33%;float:left;text-align:center;">
	<strong>February 2016</strong><br /><br />
	<?php echo $calendar3Html; ?>
</div>





<!-- br style="clear:both;" /><br style="clear:both;" />

<div class="timeOffCategory" data-category="pto">
	PTO<br />
	38.66 hr
</div>
<div class="timeOffCategory" data-category="float">
	Float<br />
	8.00 hr
</div>
<div class="timeOffCategory" data-category="sick">
	Sick<br />
	0.00 hr
</div-->

<br /><br/ >

<br style="clear:both;" />
<br style="clear:both;" />
<br style="clear:both;" />

<style>
th, td {
	border: 1px solid #000;
	padding: 5px;
}

tr.calendar-header-adjust {
	height:20px;
}

td.calendar-day {
	min-height: 20px !important;
	font-size: 11px;
	position: relative;
}

* html div.calendar-day {
	height: 20px;
}

td.calendar-day:hover {
	
}

td.calendar-day-np {
	min-height: 20px;
}

* html div.calendar-day-np {
	height: 20px;
}
</style>

<?php /**
<table>
	<thead>
		<tr>
			<th style="width: 150px;"></th>
			<th style="width: 150px;">PTO</th>
			<th style="width: 150px;">Float</th>
			<th style="width: 150px;">Sick</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><strong>Available</strong></td>
			<td><?php echo number_format($employeeData->PTO_AVAILABLE, 2); ?></td>
			<td><?php echo number_format($employeeData->FLOAT_AVAILABLE, 2); ?></td>
			<td><?php echo number_format($employeeData->SICK_AVAILABLE, 2); ?></td>
		</tr>
		<tr>
			<td><strong>Pending</strong></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td><strong>Remaining</strong></td>
			<td><?php echo number_format($employeeData->PTO_AVAILABLE, 2); ?></td>
			<td><?php echo number_format($employeeData->FLOAT_AVAILABLE, 2); ?></td>
			<td><?php echo number_format($employeeData->SICK_AVAILABLE, 2); ?></td>
		</tr>
		<tr>
			<td><strong>Requested</strong></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
	</tbody>
</table>

<br />
<br />

EMPLOYEE DATA:
<pre>
<?php print_r($employeeData); ?>
</pre>

APPROVED TIME OFF REQUEST DATA FOR THIS EMPLOYEE:
<pre>
<?php print_r($approvedRequestData); ?>
</pre>
**/ ?>