<h4>Create New Time Off Request</h4>

<br />

<?php echo $this->partial('request/partials/submitRequestWizardWidget.phtml'); ?>

<br />

<div id="noCategorySelected" style="display:none;">
    <div class="alert alert-danger" role="alert">
        <strong>You must select a category below before you select additional day(s) off.</strong>
    </div>
</div>

<?php echo $this->partial('request/partials/categoryButtonsWidget.phtml'); ?>

<br />

<?php echo $this->partial('request/partials/threeCalendarWidget.phtml'); ?>

<br />
<br />

<?php echo $this->partial('request/partials/calendarLegendWidget.phtml'); ?>

<br />
<br />

<div id="noDatesSelectedWarning" style="display:none;">
    <div class="alert alert-danger" role="alert">
        <strong>No dates are currently selected.</strong>
    </div>
</div>

<?php echo $this->partial('request/partials/requestSubmitFormWidget.phtml'); ?>
<?php echo $this->partial('request/partials/submitRequestWizardWidget.phtml'); ?>

<?php echo $this->partial('request/partials/dialogGrandfatheredAlertWidget.phtml'); ?>

<script type="text/javascript" src="<?php echo $this->basepath(); ?>/js/bootstrap-typeahead.js"></script>
<script type="text/javascript" src="<?php echo $this->basepath(); ?>/js/request/timeOffCreateRequestHandler.js"></script>
<script type="text/javascript" src="<?php echo $this->basepath(); ?>/js/select2/select2.min.js"></script>