<h4>Edit Employee Profile</h4>

<br />

<div class="tab-pane" id="tab-demo5">
    <div class="col-md-1 col-lg-1 moveDown">
        <strong>Proxies:</strong>
    </div>
    <div class="col-md-8 col-lg-8">
        <div id="warnNoProxiesSelected" style="display:none;">
            <div class="alert alert-danger" role="alert">
                <i class="fa fa-warning"></i> <strong>You do not have any proxies set up.</strong>
            </div>
        </div>
        
        <div id="warnErrorLoadingProxies" style="display:none;">
            <div class="alert alert-danger" role="alert">
                <i class="fa fa-warning"></i> <strong>Error loading proxies.</strong>
            </div>
        </div>
        
        <table class="employeeProxies">
            <thead>
                <tr>
                    <th>Name</th>
                </tr>
            </thead>
            <tbody id="employeeProxiesBody">
            </tbody>
        </table>
        
        <br style="clear:both;" />
        
        <select id="requestFor" class="requestFor form-control">
        </select><span class="categoryCloseIcon requestIsForMe glyphicon glyphicon-remove-circle red"></span>
        <br />
        <br />
        <button type="button" class="btn btn-form-primary btn-lg submitAddProxyRequest">Add Proxy</button>
    </div>
    <div class="col-md-3 col-lg-3">
        
    </div>
</div>

<br style="clear:both;" />

<script type="text/javascript" src="<?php echo $this->basepath(); ?>/js/bootstrap-typeahead.js"></script>
<script type="text/javascript" src="<?php echo $this->basepath(); ?>/js/select2/select2.min.js"></script>
<!--script type="text/javascript" src="<?php echo $this->basepath(); ?>/js/request/timeOffCreateRequestHandler.js"></script-->
<script type="text/javascript" src="<?php echo $this->basepath(); ?>/js/request/timeOffProxyHandler.js"></script>