<h4>Allow Others to Request on My Behalf</h4>

<div class="alert alert-info" role="alert">
    Here, you may select proxies, or other individuals that can submit Time Off requests on your behalf.
</div>

<table id="proxy-list" class="display" style="width:100%;">
    <thead>
        <tr>
            <th style="width:550px;">Employee</th>
            <th>Active</th>
            <th style="width:225px;">Actions</th>
        </tr>
    </thead>
</table>

<select id="requestFor" class="requestFor form-control">
</select><span class="categoryCloseIcon requestIsForMe glyphicon glyphicon-remove-circle red"></span>
<br /><br />
<button type="button" class="btn btn-form-primary btn-sm submitAddProxyRequest">Add Proxy</button>
<button type="button" class="btn btn-form-primary btn-sm clearProxyRequest">Clear</button>

<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/datatables/datatables.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/request/timeOffProxyHandler.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/request/timeOffEmployeeProfileHandler.js"></script>
<script type="text/javascript" src="<?php echo $this->basepath(); ?>/js/bootstrap-typeahead.js"></script>
<script type="text/javascript" src="<?php echo $this->basepath(); ?>/js/select2/select2.min.js"></script>

<?php echo $this->partial( 'request/partials/dialogSelectAProxy.phtml' ); ?>


<br /><br />


<h4>Manage Calendar Invites</h4>

<strong>Send me calendar invites for requests made for me</strong><br />
<div class="switch">
    <input id="cmn-toggle-1" class="cmn-toggle cmn-toggle-round-flat" type="checkbox"
           data-proxy-employee-number="123123"
           data-status="blah">
    <label for="cmn-toggle-1"></label>
</div>

<?php if( $isManager=="Y" ) { ?>
<strong>Send me calendar invites for my reports (direct and indirect)</strong><br />
<div class="switch">
    <input id="cmn-toggle-2" class="cmn-toggle cmn-toggle-round-flat" type="checkbox"
           data-proxy-employee-number="123123"
           data-status="blah">
    <label for="cmn-toggle-2"></label>
</div>
<?php } ?>