<div class="row">
  <div class="col-lg-3">&nbsp;</div>
  <div class="col-lg-6">

    <?php //if($loginError!='') { ?>
        <div class="alert alert-danger" role="alert">Login error will appear here...</div>
    <?php //} ?>

    <form class="form-horizontal" role="form" method="post">
      <div class="alert alert-info" role="info">Please login</div>
      <div class="form-group">
        <label for="username" class="control-label login-label">Username</label>
        <input type="text" placeholder="username" class="form-control"
          name="username" value="">
        <div class="red-font">
          <small><em>Username error will appear here...</em></small>
        </div>

        <label for="password" class="control-label login-label">Password</label>
        <input type="password" placeholder="password" class="form-control"
          name="password" value="">
        <div class="red-font">
          <small><em>Password error will appear here...</em></small>
        </div>

        <br />

        <button class="btn btn-custom-primary btn-lg btn-block btn-default"
          name="login" type="submit" id="login">
          <i class="fa fa-arrow-circle-o-right"></i> Login
        </button>

    </form>
  </div>

</div>
<div class="col-lg-3">&nbsp;</div>

</div>