<h4>Manage Company Holidays</h4>

<br />

<table id="company-holiday-list" class="display" style="width:100%;">
    <thead>
        <tr>
            <th style="width:550px;">Date</th>
            <th style="width:225px;">Actions</th>
        </tr>
    </thead>
</table>

<br /><br />

<input name="newCompanyHoliday" id="newCompanyHoliday">
<button type="button" class="btn btn-form-primary btn-sm submitAddCompanyHoliday">Add Company Holiday</button>

<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/datatables/datatables.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/request/timeOffCompanyHolidayHandler.js"></script>
<script type="text/javascript" src="<?php echo $this->basepath(); ?>/js/bootstrap-typeahead.js"></script>
<script type="text/javascript" src="<?php echo $this->basepath(); ?>/js/select2/select2.min.js"></script>

<script>
$( "#newCompanyHoliday" ).datepicker({
  dateFormat: "mm/dd/yy"
});
var reloadByStatusDT = function() {
    var table = $('#payroll-queue-by-status').DataTable();
    table.ajax.reload();
}
</script>

<?php echo $this->partial( 'request/partials/dialogConfirmDeleteCompanyHolidayAlertWidget.phtml' ); ?>