<h4>Manage Supervisor Proxies</h4>
<br />
<div class="row">
    <div class="col-sm-12">
        <div class="widget widgetSupervisorProxies">
            <div class="widget-content">
                <table id="widgetSupervisorProxiesDataTable"
                    class="datatable table">
                    <thead>
                        <tr>
                            <th>Supervisor</th>
                            <th>Proxy</th>
                            <th>Active</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>
<br />
<br />
<div class="row">
    <div id="addNewProxyDiv" class="col-sm-12">
        <div class="form-group">
            <label class="control-label" for="newProxyEmployee">Manager/Supervisor</label>
            <div class="input-group col-sm-6">
                <select id="newProxyEmployee" class="form-control"></select>
            </div>
        </div>
        <div class="form-group">
            <label for="newProxyEmployee">Proxy Employee</label>
            <div class="input-group col-sm-6">
                <select id="newProxyEmployeeProxy" class="form-control"></select>
            </div>
        </div>
    </div>
</div>
<div class="rowWrapper"></div>
<div>
    <button type="button" class="btn btn-form-primary btn-sm" disabled
        id="addNewProxyButton">Add new proxy</button>
    <button type="button" id="clearProxyEmployeeButton"
        class="btn btn-form-primary btn-sm clearProxyEmployee">Clear</button>
</div>
<div id="dialog-confirm" title="Remove proxy" class="hidden">
    <p>
        <span class="ui-icon ui-icon-alert"
            style="float: left; margin: 12px 12px 20px 0;"></span>The
        proxy setting will be permanently deleted and cannot be
        recovered. Are you sure?
    </p>
</div>

<script type="text/javascript"
    src="<?php echo $this->basePath(); ?>/js/datatables/datatables.js"></script>
<!-- <script type="text/javascript" src="<?php echo $this->basepath(); ?>/js/bootstrap-typeahead.js"></script> -->
<script type="text/javascript"
    src="<?php echo $this->basepath(); ?>/js/select2/select2.min.js"></script>
<script type="text/javascript"
    src="<?php echo $this->basePath(); ?>/js/request/timeOffSupervisorProxies.js"></script>