<h4>View My Requests</h4>

<br style="clear:both;" />

<div id="noCategorySelected" style="display:none;">
    <div class="alert alert-danger" role="alert">
        <strong>You must select a category below before you select additional day(s) off.</strong>
    </div>
</div>

<div class="row gutter-10">
    <div class="col-md-3 col-sm-3 col-xs-12 buttonDisappearGrandfathered">
        <button type="button" class="btn btn-requestCategory btn-lg btn-block selectTimeOffCategory buttonAllowForIcon categoryGrandfathered" data-category="timeOffGrandfathered">
            <span class="timeOffGrandfatheredCloseIcon"></span>
            <table style="width:100%;">
                <thead>
                    <tr>
                        <th colspan=2 style="text-align:center;border:0px;">Grandfathered</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="text-align:right;font-size:10px;border:0px;">Pending</td>
                        <td style="text-align:left;font-size:10px;border:0px;"><span class="hours" id="employeeGrandfatheredPendingHours"></span></td>
                    </tr>
                    <tr>
                        <td style="text-align:right;font-size:14px;border:0px;">Available</td>
                        <td style="text-align:left;font-size:14px;border:0px;"><span class="hours" id="employeeGrandfatheredAvailableHours"></span></td>
                    </tr>
                </tbody>
            </table>
        </button>
    </div>
    <div class="col-md-3 col-sm-3 col-xs-12 buttonDisappearPTO">
        <button type="button" class="btn btn-requestCategory btn-lg btn-block selectTimeOffCategory buttonAllowForIcon categoryPTO" data-category="timeOffPTO">
            <span class="timeOffPTOCloseIcon"></span>
            <table style="width:100%;">
                <thead>
                    <tr>
                        <th colspan=2 style="text-align:center;border:0px;">PTO</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="text-align:right;font-size:10px;border:0px;">Pending</td>
                        <td style="text-align:left;font-size:10px;border:0px;"><span class="hours" id="employeePTOPendingHours"></span></td>
                    </tr>
                    <tr>
                        <td style="text-align:right;font-size:14px;border:0px;">Available</td>
                        <td style="text-align:left;font-size:14px;border:0px;"><span class="hours" id="employeePTOAvailableHours"></span></td>
                    </tr>
                </tbody>
            </table>
        </button>
    </div>
    <div class="col-md-3 col-sm-3 col-xs-12 buttonDisappearFloat">
        <button type="button" class="btn btn-requestCategory btn-lg btn-block selectTimeOffCategory buttonAllowForIcon categoryFloat" data-category="timeOffFloat">
            <span class="timeOffFloatCloseIcon"></span>
            <table style="width:100%;">
                <thead>
                    <tr>
                        <th colspan=2 style="text-align:center;border:0px;">Float</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="text-align:right;font-size:10px;border:0px;">Pending</td>
                        <td style="text-align:left;font-size:10px;border:0px;"><span class="hours" id="employeeFloatPendingHours"></span></td>
                    </tr>
                    <tr>
                        <td style="text-align:right;font-size:14px;border:0px;">Available</td>
                        <td style="text-align:left;font-size:14px;border:0px;"><span class="hours" id="employeeFloatAvailableHours"></span></td>
                    </tr>
                </tbody>
            </table>
        </button>
    </div>
    <div class="col-md-3 col-sm-3 col-xs-12 buttonDisappearSick">
        <button type="button" class="btn btn-requestCategory btn-lg btn-block selectTimeOffCategory buttonAllowForIcon categorySick" data-category="timeOffSick">
            <span class="timeOffSickCloseIcon"></span>
            <table style="width:100%;">
                <thead>
                    <tr>
                        <th colspan=2 style="text-align:center;border:0px;">Sick</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="text-align:right;font-size:10px;border:0px;">Pending</td>
                        <td style="text-align:left;font-size:10px;border:0px;"><span class="hours" id="employeeSickPendingHours"></span></td>
                    </tr>
                    <tr>
                        <td style="text-align:right;font-size:14px;border:0px;">Available</td>
                        <td style="text-align:left;font-size:14px;border:0px;"><span class="hours" id="employeeSickAvailableHours"></span></td>
                    </tr>
                </tbody>
            </table>
        </button>
    </div>
</div>

<br style="clear:both;" />

<div class="row gutter-10">
    <div class="col-md-3 col-sm-3 col-xs-12 buttonDisappearUnexcusedAbsence">
        <button type="button" class="btn btn-requestCategory btn-lg btn-block selectTimeOffCategory buttonAllowForIcon categoryUnexcusedAbsence" data-category="timeOffUnexcusedAbsence">
            <span class="timeOffUnexcusedAbsenceCloseIcon"></span>
            <table style="width:100%;">
                <thead>
                    <tr>
                        <th colspan=2 style="text-align:center;border:0px;">Unexcused</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="text-align:right;font-size:10px;border:0px;">Pending</td>
                        <td style="text-align:left;font-size:10px;border:0px;"><span class="hours" id="employeeUnexcusedAbsencePendingHours"></span></td>
                    </tr>
                    <?php /*                     * *<tr>
                      <td style="text-align:right;font-size:14px;border:0px;">Available</td>
                      <td style="text-align:left;font-size:14px;border:0px;"><span class="hours" id="employeeUnexcusedAbsenceAvailableHours"></span></td>
                      </tr> ** */ ?>
                </tbody>
            </table>
        </button>
    </div>
    <div class="col-md-3 col-sm-3 col-xs-12 buttonDisappearBereavement">
        <button type="button" class="btn btn-requestCategory btn-lg btn-block selectTimeOffCategory buttonAllowForIcon categoryBereavement" data-category="timeOffBereavement">
            <span class="timeOffBereavementCloseIcon"></span>
            <table style="width:100%;">
                <thead>
                    <tr>
                        <th colspan=2 style="text-align:center;border:0px;">Bereavement</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="text-align:right;font-size:10px;border:0px;">Pending</td>
                        <td style="text-align:left;font-size:10px;border:0px;"><span class="hours" id="employeeBereavementPendingHours"></span></td>
                    </tr>
                    <?php /*                     * *<tr>
                      <td style="text-align:right;font-size:14px;border:0px;">Available</td>
                      <td style="text-align:left;font-size:14px;border:0px;"><span class="hours" id="employeeBereavementAvailableHours"></span></td>
                      </tr> ** */ ?>
                </tbody>
            </table>
        </button>
    </div>
    <div class="col-md-3 col-sm-3 col-xs-12 buttonDisappearCivicDuty">
        <button type="button" class="btn btn-requestCategory btn-lg btn-block selectTimeOffCategory buttonAllowForIcon categoryCivicDuty" data-category="timeOffCivicDuty">
            <span class="timeOffCivicDutyCloseIcon"></span>
            <table style="width:100%;">
                <thead>
                    <tr>
                        <th colspan=2 style="text-align:center;border:0px;">Civic Duty</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="text-align:right;font-size:10px;border:0px;">Pending</td>
                        <td style="text-align:left;font-size:10px;border:0px;"><span class="hours" id="employeeCivicDutyPendingHours"></span></td>
                    </tr>
                    <?php /*                     * *<tr>
                      <td style="text-align:right;font-size:14px;border:0px;">Available</td>
                      <td style="text-align:left;font-size:14px;border:0px;"><span class="hours" id="employeeCivicDutyAvailableHours"></span></td>
                      </tr> ** */ ?>
                </tbody>
            </table>
        </button>
    </div>
    <div class="col-md-3 col-sm-3 col-xs-12 buttonDisappearApprovedNoPay">
        <button type="button" class="btn btn-requestCategory btn-lg btn-block selectTimeOffCategory buttonAllowForIcon categoryApprovedNoPay" data-category="timeOffApprovedNoPay">
            <span class="timeOffApprovedNoPayCloseIcon"></span>
            <table style="width:100%;">
                <thead>
                    <tr>
                        <th colspan=2 style="text-align:center;border:0px;">Approved Without Pay</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="text-align:right;font-size:10px;border:0px;">Pending</td>
                        <td style="text-align:left;font-size:10px;border:0px;"><span class="hours" id="employeeApprovedNoPayPendingHours"></span></td>
                    </tr>
                    <?php /*                     * *<tr>
                      <td style="text-align:right;font-size:14px;border:0px;">Available</td>
                      <td style="text-align:left;font-size:14px;border:0px;"><span class="hours" id="employeeApprovedNoPayAvailableHours"></span></td>
                      </tr> ** */ ?>
                </tbody>
            </table>
        </button>
    </div>
</div>

<br style="clear:both;" />

<?php /* * ***
  <div class="row gutter-10">
  <div class="col-md-3">
  <div class="selectTimeOffCategory timeOffCategoryLeft timeOffPTO cursorHand" data-category="timeOffPTO">
  &nbsp;<br />&nbsp;
  </div>
  <div class="selectTimeOffCategory timeOffCategory cursorHand" data-category="timeOffPTO">
  PTO<br />
  <span class="hours" id="employeePTOHours"></span>
  </div>
  </div>
  <div class="col-md-3">
  <div class="selectTimeOffCategory timeOffCategoryLeft timeOffFloat cursorHand" data-category="timeOffFloat">
  &nbsp;<br />&nbsp;
  </div>
  <div class="selectTimeOffCategory timeOffCategory cursorHand" data-category="timeOffFloat">
  Float<br />
  <span class="hours" id="employeeFloatHours"></span>
  </div>
  </div>
  <div class="col-md-3">
  <div class="selectTimeOffCategory timeOffCategoryLeft timeOffSick cursorHand" data-category="timeOffSick">
  &nbsp;<br />&nbsp;
  </div>
  <div class="selectTimeOffCategory timeOffCategory cursorHand" data-category="timeOffSick">
  Sick<br />
  <span class="hours" id="employeeSickHours"></span>
  </div>
  </div>
  <div class="col-md-3">
  <div class="selectTimeOffCategory timeOffCategoryLeft timeOffGrandfathered cursorHand" data-category="timeOffGrandfathered">
  &nbsp;<br />&nbsp;
  </div>
  <div class="selectTimeOffCategory timeOffCategory cursorHand" data-category="timeOffGrandfathered">
  Grandfathered<br />
  <span class="hours" id="employeeGrandfatheredHours"></span>
  </div>
  </div>
  </div>

  <br style="clear:both;" />

  <div class="row gutter-10">
  <div class="col-md-3">
  <div class="selectTimeOffCategory timeOffCategoryLeft timeOffUnexcusedAbsence cursorHand" data-category="timeOffUnexcusedAbsence">
  &nbsp;<br />&nbsp;
  </div>
  <div class="selectTimeOffCategory timeOffCategory cursorHand" data-category="timeOffUnexcusedAbsence">
  Unexcused<br />
  <span class="hours" id="employeeUnexcusedAbsenceHours"></span>
  </div>
  </div>
  <div class="col-md-3">
  <div class="selectTimeOffCategory timeOffCategoryLeft timeOffBereavement cursorHand" data-category="timeOffBereavement">
  &nbsp;<br />&nbsp;
  </div>
  <div class="selectTimeOffCategory timeOffCategory cursorHand" data-category="timeOffBereavement">
  Bereavement<br />
  <span class="hours" id="employeeBereavementHours"></span>
  </div>
  </div>
  <div class="col-md-3">
  <div class="selectTimeOffCategory timeOffCategoryLeft timeOffCivicDuty cursorHand" data-category="timeOffCivicDuty">
  &nbsp;<br />&nbsp;
  </div>
  <div class="selectTimeOffCategory timeOffCategory cursorHand" data-category="timeOffCivicDuty">
  Civic Duty<br />
  <span class="hours" id="employeeCivicDutyHours"></span>
  </div>
  </div>
  <div class="col-md-3">
  <div class="selectTimeOffCategory timeOffCategoryLeft timeOffApprovedNoPay cursorHand" data-category="timeOffApprovedNoPay">
  &nbsp;<br />&nbsp;
  </div>
  <div class="selectTimeOffCategory timeOffCategory cursorHand" data-category="timeOffApprovedNoPay">
  Approved No Pay<br />
  <span class="hours" id="employeeApprovedNoPayHours"></span>
  </div>
  </div>
  </div>
 * * */ ?>

<div id="timeOffCalendarWrapper">
    <div id="timeOffCalendarWarningNoCategorySelected">
        <div class="alert alert-danger" role="alert">
            <span class="glyphicon glyphicon-warning-sign pull-left" aria-hidden="true"></span>&nbsp;&nbsp;
            <strong>Sorry!</strong>&nbsp;Before you select any dates, please select a category above.
        </div>
    </div>
    <div style="width:33%;padding-right:10px;float:left;text-align:center;" id="calendar1Html">
        <?php /*         * *<strong>December 2015</strong><br /><br />
          <?php echo $calendar1Html; * */ ?>
    </div>
    <div style="width:33%;padding-right:10px;float:left;text-align:center;" id="calendar2Html">
        <?php /*         * *<strong>January 2016</strong><br /><br />
          <?php echo $calendar2Html; ?> * */ ?>
    </div>
    <div style="width:33%;float:left;text-align:center;" id="calendar3Html">
        <?php /*         * *<strong>February 2016</strong><br /><br />
          <?php echo $calendar3Html; ?> * */ ?>
    </div>
    
    <br style="clear:both;" />
    <br style="clear:both;" />
    
    <div id="calendarLegend">
        <div class="legend-title">
            <strong>Request Types by Color</strong><br />
            <i>Note: Approved requests appear in a solid color.<br />
                Pending requests appear in a lighter version of each color.</i>
            <div class="timeOffCalendarLegend">
                <div class="legend-scale">
                    <ul class="legend-labels">
                        <li><span style="background:#f57900;"></span>PTO</li>
                        <li><span style="background:#edd400;"></span>Float</li>
                        <li><span style="background:#73d216;"></span>Sick</li>
                        <li><span style="background:#888a85;"></span>Unexcused</li>
                        <li><span style="background:#729fcf;"></span>Bereavement</li>
                        <li><span style="background:#75507b;"></span>Civic Duty</li>
                        <li><span style="background:#c17d11;"></span>Grandfathered</li>
                        <li><span style="background:#cc0000;"></span>No Pay</li>
                        <li><span style="background:#404040;"></span>Holiday</li>
                    </ul>
                </div>
            </div>
            <br />
            <br />
        </div>
        
    </div>
</div>

<br style="clear:both;" />

<button type="button" class="btn btn-primary-form btn-xs toggleLegend">Show/hide legend</button>

<br style="clear:both;" />
<br style="clear:both;" />

<span class="glyphicon glyphicon-ok green"></span>&nbsp;Approved time off<br />
<span class="glyphicon glyphicon-user red"></span>&nbsp;Pending approval<br />

<!-- div class="row gutter-10 timeOffCalendarWrapper">
    <div class="col-md-4" id="calendar1Html">
                
        </div>
        <div class="col-md-4" id="calendar2Html">
                
        </div>
        <div class="col-md-4" id="calendar3Html">
                
        </div>
</div-->

<div class="row gutter-10 timeOffCalendarWrapper">
    <div class="col-md-4">

    </div>
    <div class="col-md-4" id="datesSelectedDetails2" style="display: block;">
        <!--strong>Hours Requested:</strong><br style="clear:both;"><br style="clear:both;">
        
        02/01/2016&nbsp;&nbsp;&nbsp;&nbsp;<input class="selectedDateHours" value="8.00" size="2" data-key="0" disabled="disabled">&nbsp;&nbsp;&nbsp;&nbsp;<span class="badge timeOffPTO">PTO</span>&nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-ok green" data-date="02/01/2016" data-category="timeOffPTO" title="Approved"></span><br style="clear:both;">
        02/08/2016&nbsp;&nbsp;&nbsp;&nbsp;<input class="selectedDateHours" value="8.00" size="2" data-key="1" disabled="disabled">&nbsp;&nbsp;&nbsp;&nbsp;<span class="badge timeOffPTO">PTO</span>&nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-user red" data-date="02/08/2016" data-category="timeOffPTO" title="Pending Manager Approval"></span><br style="clear:both;">
        02/09/2016&nbsp;&nbsp;&nbsp;&nbsp;<input class="selectedDateHours" value="8.00" size="2" data-key="2" disabled="disabled">&nbsp;&nbsp;&nbsp;&nbsp;<span class="badge timeOffPTO">PTO</span>&nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-user red" data-date="02/09/2016" data-category="timeOffPTO" title="Pending Manager Approval"></span><br style="clear:both;">
        02/11/2016&nbsp;&nbsp;&nbsp;&nbsp;<input class="selectedDateHours" value="8.00" size="2" data-key="3" disabled="disabled">&nbsp;&nbsp;&nbsp;&nbsp;<span class="badge timeOffPTO">PTO</span>&nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-user red" data-date="02/11/2016" data-category="timeOffPTO" title="Pending Manager Approval"></span><br style="clear:both;">
        02/12/2016&nbsp;&nbsp;&nbsp;&nbsp;<input class="selectedDateHours" value="8.00" size="2" data-key="4" disabled="disabled">&nbsp;&nbsp;&nbsp;&nbsp;<span class="badge timeOffPTO">PTO</span>&nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-user red" data-date="02/12/2016" data-category="timeOffPTO" title="Pending Manager Approval"></span><br style="clear:both;">
        02/15/2016&nbsp;&nbsp;&nbsp;&nbsp;<input class="selectedDateHours" value="8.00" size="2" data-key="4" disabled="disabled">&nbsp;&nbsp;&nbsp;&nbsp;<span class="badge timeOffPTO">PTO</span>&nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-user red" data-date="02/15/2016" data-category="timeOffPTO" title="Pending Manager Approval"></span><br style="clear:both;">
        02/17/2016&nbsp;&nbsp;&nbsp;&nbsp;<input class="selectedDateHours" value="8.00" size="2" data-key="4" disabled="disabled">&nbsp;&nbsp;&nbsp;&nbsp;<span class="badge timeOffPTO">PTO</span>&nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-user red" data-date="02/17/2016" data-category="timeOffPTO" title="Pending Manager Approval"></span><br style="clear:both;">
        02/18/2016&nbsp;&nbsp;&nbsp;&nbsp;<input class="selectedDateHours" value="8.00" size="2" data-key="4" disabled="disabled">&nbsp;&nbsp;&nbsp;&nbsp;<span class="badge timeOffPTO">PTO</span>&nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-user red" data-date="02/18/2016" data-category="timeOffPTO" title="Pending Manager Approval"></span><br style="clear:both;">
        
        <br style="clear:both;"-->
        
        <?php /***
        <strong>Reason for request:</strong>
        
        <br style="clear:both;"><br style="clear:both;">
        
        <textarea cols="40" rows="4" id="requestReason"></textarea>
        
        <br><br>
        
        <button type="button" class="btn btn-form-primary btn-lg submitTimeOffRequest">Submit My Request</button>
        
        <br style="clear:both;"><br style="clear:both;">
        ***/ ?>
        
    </div>
    <div class="col-md-4">

    </div>
</div>

<div id="noDatesSelectedWarning" style="display:none;">
    <div class="alert alert-danger" role="alert">
        <strong>No dates are currently selected.</strong>
    </div>
</div>

<!-- div id="datesSelectedDetails"></div-->

<div class="row gutter-10 timeOffCalendarWrapper">
    <div class="col-md-4">

    </div>
    <div class="col-md-4" id="datesSelectedDetails">

    </div>
    <div class="col-md-4">

    </div>
</div>

<br style="clear:both;" />

<?php /***
<br style="clear:both;" />
<br style="clear:both;" />
<br style="clear:both;" />

<div id="MyWizard" class="wizard">
    <ul class="steps">
        <li data-target="#step1" class="step1 active"><span class="badge badge-info">1</span>Select a Category<span class="chevron"></span></li>
        <li data-target="#step2" class="step2"><span class="badge">2</span>Select date(s)<span class="chevron"></span></li>
        <li data-target="#step3" class="step3 last"><span class="badge">3</span>Provide a Reason & Submit</li>
    </ul>
</div>
***/ ?>

<!-- br style="clear:both;" /><br style="clear:both;" />

<div class="timeOffCategory" data-category="pto">
        PTO<br />
        38.66 hr
</div>
<div class="timeOffCategory" data-category="float">
        Float<br />
        8.00 hr
</div>
<div class="timeOffCategory" data-category="sick">
        Sick<br />
        0.00 hr
</div-->

<br /><br />

    <br style="clear:both;" />
<br style="clear:both;" />
<br style="clear:both;" />

<div id="dialogGrandfatheredAlert" title="Grandfathered Time Alert">
    <p>
        It appears you have a balance of Grandfathered time. Please take this time first before using PTO time.<br /><br />
        If you end up with less than 8 hours, please use up your balance as much as possible, submit your request, and contact your manager to use the balance.
    </p>
</div>