<h4>View My Requests</h4>

<br />

<?php echo $this->partial('request/partials/categoryButtonsWidget.phtml'); ?>

<br />

<?php echo $this->partial('request/partials/threeCalendarWidget.phtml'); ?>

<br style="clear:both;" />
<br style="clear:both;" />

<?php echo $this->partial('request/partials/calendarLegendWidget.phtml'); ?>

<br />
<br />

<span class="glyphicon glyphicon-ok green"></span>&nbsp;Approved time off<br />
<span class="glyphicon glyphicon-user red"></span>&nbsp;Pending approval<br />

<div id="noDatesSelectedWarning" style="display:none;">
    <br />
    <div class="alert alert-danger" role="alert">
        <strong>No dates are requested during the period shown.</strong>
    </div>
</div>

<div class="row gutter-10">
    <div class="col-md-4">

    </div>
    <div class="col-md-4" id="datesSelectedDetails">
        
    </div>
    <div class="col-md-4">

    </div>
</div>

<?php echo $this->partial('request/partials/dialogGrandfatheredAlertWidget.phtml'); ?>

<script type="text/javascript" src="<?php echo $this->basepath(); ?>/js/bootstrap-typeahead.js"></script>
<script type="text/javascript" src="<?php echo $this->basepath(); ?>/js/request/timeOffViewMyRequestHandler.js"></script>
<script type="text/javascript" src="<?php echo $this->basepath(); ?>/js/select2/select2.min.js"></script>