<div class="row gutter-10">
    <div class="col-sm-6 col-md-6 col-lg-6">
    	<h4>View My Requests</h4>
    </div>
    <div class="col-sm-6 col-md-6 col-lg-6 text-right">
    	<a href="<?php echo $this->basePath(); ?>/request/create">
    		<button type="button" class="btn btn-form-primary btn-md">Create New Request</button>
    	</a>
    </div>
</div>

<br />

<?php echo $this->partial('request/partials/categoryButtonsWidget.phtml'); ?>

<br />

<?php echo $this->partial('request/partials/threeCalendarWidget.phtml'); ?>

<br style="clear:both;" />
<br style="clear:both;" />

<?php echo $this->partial('request/partials/calendarLegendWidget.phtml'); ?>

<br />
<br />

<span class="glyphicon glyphicon-ok green"></span>&nbsp;Approved time off<br />
<span class="glyphicon glyphicon-user red"></span>&nbsp;Pending approval<br />

<div id="noDatesSelectedWarning" style="display:none;">
    <br />
    <div class="alert alert-info" role="alert">
        <i class="fa fa-info-circle"></i> <strong>No dates are requested during the period shown.</strong>
    </div>
</div>

<div class="row gutter-10">
    <div class="col-md-3 col-lg-3">

    </div>
    <div class="col-md-6 col-lg-6" id="datesSelectedDetails">
        
    </div>
    <div class="col-md-3 col-lg-3">

    </div>
</div>

<?php echo $this->partial('request/partials/dialogGrandfatheredAlertWidget.phtml'); ?>

<script type="text/javascript" src="<?php echo $this->basepath(); ?>/js/bootstrap-typeahead.js"></script>
<script type="text/javascript" src="<?php echo $this->basepath(); ?>/js/request/timeOffViewMyRequestHandler.js"></script>
<script type="text/javascript" src="<?php echo $this->basepath(); ?>/js/request/timeOffCreateRequestHandler.js"></script>
<script type="text/javascript" src="<?php echo $this->basepath(); ?>/js/select2/select2.min.js"></script>