<?php

$title = 'Delete album';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
 '<?php echo $this->escapeHtml($album->TITLE); ?>' by
 '<?php echo $this->escapeHtml($album->ARTIST); ?>'?
</p>
<?php
$url = $this->url('album', array(
 'action' => 'delete',
 'id'     => $this->IDENTITY_ID,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
 <input type="hidden" name="IDENTITY_ID" value="<?php echo (int) $album->IDENTITY_ID; ?>" />
 <input type="submit" name="del" value="Yes" />
 <input type="submit" name="del" value="No" />
</div>
</form>
