<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Edit album';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
 'album',
 array(
     'action' => 'edit',
     'IDENTITY_ID' => $this->IDENTITY_ID,
 )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('IDENTITY_ID'));
echo $this->formRow($form->get('TITLE'));
echo '<br />';
echo $this->formRow($form->get('ARTIST'));
echo '<br />';
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
