<div id="calendarLegend">
    <div class="legend-title">
        <strong>Request Types by Color</strong><br />
        <i>Note: Approved requests appear in a solid color. Pending and approved requests appear in a lighter version of each color. See also the legend above "Hours Requested".</i>
        <div class="timeOffCalendarLegend">
            <div class="legend-scale">
                <ul class="legend-labels">
                    <li><span style="width:40px;background:#f57900;"></span><span style="width:40px;">PTO</span></li>
                    <li><span style="width:40px;background:#edd400;"></span><span style="width:40px;">Float</span></li>
                    <li><span style="width:40px;background:#73d216;"></span><span style="width:40px;">Sick</span></li>
                    <li><span style="width:40px;background:#888a85;"></span><span style="width:40px;">Unexcused</span></li>
                    <li><span style="width:40px;background:#729fcf;"></span><span style="width:65px;">Bereavement</span></li>
                </ul>
            </div>
            <br style="clear:both;">
            <div class="legend-scale">
                <ul class="legend-labels">
                    <li><span style="width:40px;background:#75507b;"></span><span style="width:40px;">Civic Duty</span></li>
                    <li><span style="width:40px;background:#c17d11;"></span><span style="width:65px;">Grandfathered</span></li>
                    <li><span style="width:40px;background:#cc0000;"></span><span style="width:40px;">No Pay</span></li>
                    <li><span style="width:40px;background:#fff;border:3px solid #cc0000;"></span><span style="width:40px;">Today</span></li>
                    <li><span style="width:40px;background:#fff;border:3px solid fuchsia;"></span><span style="width:40px;">Holiday</span></li>
                </ul>
            </div>
        </div>
        <br />
        <br />
    </div>
</div>
<button type="button" class="btn btn-primary-form btn-xs toggleLegend">Show/hide legend</button>