<div id="calendarLegend">
    <div class="legend-title">
        <strong>Request Types by Color</strong><br />
        <i>Note: Approved requests appear in a solid color.<br />
            Pending requests appear in a lighter version of each color.</i>
        <div class="timeOffCalendarLegend">
            <div class="legend-scale">
                <ul class="legend-labels">
                    <li><span style="background:#f57900;"></span>PTO</li>
                    <li><span style="background:#edd400;"></span>Float</li>
                    <li><span style="background:#73d216;"></span>Sick</li>
                    <li><span style="background:#888a85;"></span>Unexcused</li>
                    <li><span style="background:#729fcf;"></span>Bereavement</li>
                    <li><span style="background:#75507b;"></span>Civic Duty</li>
                    <li><span style="background:#c17d11;"></span>Grandfathered</li>
                    <li><span style="background:#cc0000;"></span>No Pay</li>
                    <li><span style="background:#404040;"></span>Holiday</li>
                </ul>
            </div>
        </div>
        <br />
        <br />
    </div>   
</div>
<button type="button" class="btn btn-primary-form btn-xs toggleLegend">Show/hide legend</button>