<div class="row gutter-10 padBottomButtonRow">
    <div class="col-md-3 col-sm-3 col-xs-12 buttonDisappearGrandfathered">
        <button type="button" class="btn btn-requestCategory btn-lg btn-block selectTimeOffCategory buttonAllowForIcon categoryGrandfathered" data-category="timeOffGrandfathered">
            <span class="timeOffGrandfatheredCloseIcon"></span>
            <table style="width:100%;">
                <thead>
                    <tr>
                        <th colspan=2 style="text-align:center;border:0px;">Grandfathered</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="text-align:right;font-size:10px;border:0px;">Pending</td>
                        <td style="text-align:left;font-size:10px;border:0px;"><span class="hours" id="employeeGrandfatheredPendingHours"></span></td>
                    </tr>
                    <tr>
                        <td style="text-align:right;font-size:14px;border:0px;">Remaining</td>
                        <td style="text-align:left;font-size:14px;border:0px;"><span class="hours" id="employeeGrandfatheredRemainingHours"></span></td>
                    </tr>
                </tbody>
            </table>
        </button>
    </div>
    <div class="col-md-3 col-sm-3 col-xs-12 buttonDisappearPTO">
        <button type="button" class="btn btn-requestCategory btn-lg btn-block selectTimeOffCategory buttonAllowForIcon categoryPTO" data-category="timeOffPTO">
            <span class="timeOffPTOCloseIcon"></span>
            <table style="width:100%;">
                <thead>
                    <tr>
                        <th colspan=2 style="text-align:center;border:0px;">PTO</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="text-align:right;font-size:10px;border:0px;">Pending</td>
                        <td style="text-align:left;font-size:10px;border:0px;"><span class="hours" id="employeePTOPendingHours"></span></td>
                    </tr>
                    <tr>
                        <td style="text-align:right;font-size:14px;border:0px;">Remaining</td>
                        <td style="text-align:left;font-size:14px;border:0px;"><span class="hours" id="employeePTORemainingHours"></span></td>
                    </tr>
                </tbody>
            </table>
        </button>
    </div>
    <div class="col-md-3 col-sm-3 col-xs-12 buttonDisappearFloat">
        <button type="button" class="btn btn-requestCategory btn-lg btn-block selectTimeOffCategory buttonAllowForIcon categoryFloat" data-category="timeOffFloat">
            <span class="timeOffFloatCloseIcon"></span>
            <table style="width:100%;">
                <thead>
                    <tr>
                        <th colspan=2 style="text-align:center;border:0px;">Float</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="text-align:right;font-size:10px;border:0px;">Pending</td>
                        <td style="text-align:left;font-size:10px;border:0px;"><span class="hours" id="employeeFloatPendingHours"></span></td>
                    </tr>
                    <tr>
                        <td style="text-align:right;font-size:14px;border:0px;">Remaining</td>
                        <td style="text-align:left;font-size:14px;border:0px;"><span class="hours" id="employeeFloatRemainingHours"></span></td>
                    </tr>
                </tbody>
            </table>
        </button>
    </div>
    <div class="col-md-3 col-sm-3 col-xs-12 buttonDisappearSick">
        <button type="button" class="btn btn-requestCategory btn-lg btn-block selectTimeOffCategory buttonAllowForIcon categorySick" data-category="timeOffSick">
            <span class="timeOffSickCloseIcon"></span>
            <table style="width:100%;">
                <thead>
                    <tr>
                        <th colspan=2 style="text-align:center;border:0px;">Sick</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="text-align:right;font-size:10px;border:0px;">Pending</td>
                        <td style="text-align:left;font-size:10px;border:0px;"><span class="hours" id="employeeSickPendingHours"></span></td>
                    </tr>
                    <tr>
                        <td style="text-align:right;font-size:14px;border:0px;">Remaining</td>
                        <td style="text-align:left;font-size:14px;border:0px;"><span class="hours" id="employeeSickRemainingHours"></span></td>
                    </tr>
                </tbody>
            </table>
        </button>
    </div>
</div>
<div class="row gutter-10">
    <div class="col-md-3 col-sm-3 col-xs-12 buttonDisappearUnexcusedAbsence">
        <button type="button" class="btn btn-requestCategory btn-lg btn-block selectTimeOffCategory buttonAllowForIcon categoryUnexcusedAbsence" data-category="timeOffUnexcusedAbsence">
            <span class="timeOffUnexcusedAbsenceCloseIcon"></span>
            <table style="width:100%;">
                <thead>
                    <tr>
                        <th colspan=2 style="text-align:center;border:0px;">Unexcused</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="text-align:right;font-size:10px;border:0px;">Pending</td>
                        <td style="text-align:left;font-size:10px;border:0px;"><span class="hours" id="employeeUnexcusedAbsencePendingHours"></span></td>
                    </tr>
                    <?php /*                     * *<tr>
                      <td style="text-align:right;font-size:14px;border:0px;">Remaining</td>
                      <td style="text-align:left;font-size:14px;border:0px;"><span class="hours" id="employeeUnexcusedAbsenceRemainingHours"></span></td>
                      </tr> ** */ ?>
                </tbody>
            </table>
        </button>
    </div>
    <div class="col-md-3 col-sm-3 col-xs-12 buttonDisappearBereavement">
        <button type="button" class="btn btn-requestCategory btn-lg btn-block selectTimeOffCategory buttonAllowForIcon categoryBereavement" data-category="timeOffBereavement">
            <span class="timeOffBereavementCloseIcon"></span>
            <table style="width:100%;">
                <thead>
                    <tr>
                        <th colspan=2 style="text-align:center;border:0px;">Bereavement</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="text-align:right;font-size:10px;border:0px;">Pending</td>
                        <td style="text-align:left;font-size:10px;border:0px;"><span class="hours" id="employeeBereavementPendingHours"></span></td>
                    </tr>
                    <?php /*                     * *<tr>
                      <td style="text-align:right;font-size:14px;border:0px;">Remaining</td>
                      <td style="text-align:left;font-size:14px;border:0px;"><span class="hours" id="employeeBereavementRemainingHours"></span></td>
                      </tr> ** */ ?>
                </tbody>
            </table>
        </button>
    </div>
    <div class="col-md-3 col-sm-3 col-xs-12 buttonDisappearCivicDuty">
        <button type="button" class="btn btn-requestCategory btn-lg btn-block selectTimeOffCategory buttonAllowForIcon categoryCivicDuty" data-category="timeOffCivicDuty">
            <span class="timeOffCivicDutyCloseIcon"></span>
            <table style="width:100%;">
                <thead>
                    <tr>
                        <th colspan=2 style="text-align:center;border:0px;">Civic Duty</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="text-align:right;font-size:10px;border:0px;">Pending</td>
                        <td style="text-align:left;font-size:10px;border:0px;"><span class="hours" id="employeeCivicDutyPendingHours"></span></td>
                    </tr>
                    <?php /*                     * *<tr>
                      <td style="text-align:right;font-size:14px;border:0px;">Remaining</td>
                      <td style="text-align:left;font-size:14px;border:0px;"><span class="hours" id="employeeCivicDutyRemainingHours"></span></td>
                      </tr> ** */ ?>
                </tbody>
            </table>
        </button>
    </div>
    <div class="col-md-3 col-sm-3 col-xs-12 buttonDisappearApprovedNoPay">
        <button type="button" class="btn btn-requestCategory btn-lg btn-block selectTimeOffCategory buttonAllowForIcon categoryApprovedNoPay" data-category="timeOffApprovedNoPay">
            <span class="timeOffApprovedNoPayCloseIcon"></span>
            <table style="width:100%;">
                <thead>
                    <tr>
                        <th colspan=2 style="text-align:center;border:0px;">Time Off Without Pay</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="text-align:right;font-size:10px;border:0px;">Pending</td>
                        <td style="text-align:left;font-size:10px;border:0px;"><span class="hours" id="employeeApprovedNoPayPendingHours"></span></td>
                    </tr>
                    <?php /*                     * *<tr>
                      <td style="text-align:right;font-size:14px;border:0px;">Remaining</td>
                      <td style="text-align:left;font-size:14px;border:0px;"><span class="hours" id="employeeApprovedNoPayRemainingHours"></span></td>
                      </tr> ** */ ?>
                </tbody>
            </table>
        </button>
    </div>
</div>