<?php if ( isset( $_SESSION['Timeoff_' . ENVIRONMENT] ) && ( ENVIRONMENT=='testing' || ENVIRONMENT=='development' ) ) { ?>
<pre style="margin-top:50px;font-size:75%;">
    <strong>The following is information used for troubleshooting in non-Production environments.</strong>

    Is Manager: <?php echo $this->isManager; ?><br />
    Is Supervisor: <?php echo $this->isSupervisor; ?><br />
    Is Payroll: <?php echo $this->isPayroll; ?><br />
    Is Payroll Administrator: <?php echo $this->isPayrollAdmin; ?><br />
    Is Payroll Assistant: <?php echo $this->isPayrollAssistant; ?><br />
    Is Proxy: <?php echo $this->isProxy; ?><br />
    Is Proxy For Manager: <?php echo $this->isProxyForManager; ?><br />
</pre>
<?php } ?>