<div id="dialogEditEmployeeSchedule" title="Edit employee's schedule">
    <p class="validateTips">All form fields are required.</p>

    <div class="row">
        <div class="col-lg-3 col-md-3 text-left">
            <strong>SUN</strong>
        </div>
        <div class="col-lg-9 col-md-9">
            <input id="employeeScheduleSUN" style="width:50px;"> hours
        </div>
    </div>
    <div class="row">
        <div class="col-lg-3 col-md-3 text-left">
            <strong>MON</strong>
        </div>
        <div class="col-lg-9 col-md-9">
            <input id="employeeScheduleMON" style="width:50px;"> hours
        </div>
    </div>
    <div class="row">
        <div class="col-lg-3 col-md-3 text-left">
            <strong>TUE</strong>
        </div>
        <div class="col-lg-9 col-md-9">
            <input id="employeeScheduleTUE" style="width:50px;"> hours
        </div>
    </div>
    <div class="row">
        <div class="col-lg-3 col-md-3 text-left">
            <strong>WED</strong>
        </div>
        <div class="col-lg-9 col-md-9">
            <input id="employeeScheduleWED" style="width:50px;"> hours
        </div>
    </div>
    <div class="row">
        <div class="col-lg-3 col-md-3 text-left">
            <strong>THU</strong>
        </div>
        <div class="col-lg-9 col-md-9">
            <input id="employeeScheduleTHU" style="width:50px;"> hours
        </div>
    </div>
    <div class="row">
        <div class="col-lg-3 col-md-3 text-left">
            <strong>FRI</strong>
        </div>
        <div class="col-lg-9 col-md-9">
            <input id="employeeScheduleFRI" style="width:50px;"> hours
        </div>
    </div>
    <div class="row">
        <div class="col-lg-3 col-md-3 text-left">
            <strong>SAT</strong>
        </div>
        <div class="col-lg-9 col-md-9">
            <input id="employeeScheduleSAT" style="width:50px;"> hours
        </div>
    </div>
    
    <input id="employeeScheduleFor" type="hidden" value="">
    <input id="employeeScheduleBy" type="hidden" value="">
</div>