<table class="employeeSchedule">
    <thead>
        <tr>
            <th>SUN</th>
            <th>MON</th>
            <th>TUE</th>
            <th>WED</th>
            <th>THU</th>
            <th>FRI</th>
            <th>SAT</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td id="scheduleSUN"></td>
            <td id="scheduleMON"></td>
            <td id="scheduleTUE"></td>
            <td id="scheduleWED"></td>
            <td id="scheduleTHU"></td>
            <td id="scheduleFRI"></td>
            <td id="scheduleSAT"></td>
        </tr>
    </tbody>
</table>
