<form id="newTimeOffRequestForm">
    <div id="datesSelectedDetails" style="display:none;">

    </div>

    <br style="clear:both;"/>

    <div id="warnSalaryTakingRequiredHoursPerDay" style="display:none;">
        <div class="alert alert-danger" role="alert">
            <i class="fa fa-warning"></i> <strong>Salaried employees must take 8 hours off for each day requested.</strong>
        </div>
    </div>

    <div id="warnHourlyTakingRequiredHoursPerDay" style="display:none;">
        <div class="alert alert-danger" role="alert">
            <i class="fa fa-warning"></i> <strong>Hourly employees must take between 0-12 hours off for each day requested.</strong>
        </div>
    </div>

    <?php /***
    <div id="requestSubmitDetails" style="display:none;">
        <strong>Reason for request:</strong>
        <br style="clear:both;"/>
        <br style="clear:both;"/>
        <textarea style="width:100%;" rows="4" id="requestReason"></textarea>
        <br style="clear:both;"/>
        <br style="clear:both;"/>

        <div id="warnPTO" style="display:none;">
            <div class="alert alert-danger" role="alert">
                <i class="fa fa-warning"></i> <strong>PTO time remaining has been exceeded.</strong>
            </div>
        </div>

        <div id="warnFloat" style="display:none;">
            <div class="alert alert-danger" role="alert">
                <i class="fa fa-warning"></i> <strong>Float time remaining has been exceeded.</strong>
            </div>
        </div>

        <div id="warnSick" style="display:none;">
            <div class="alert alert-danger" role="alert">
                <i class="fa fa-warning"></i> <strong>Sick time remaining has been exceeded.</strong>
            </div>
        </div>

        <div id="warnGF" style="display:none;">
            <div class="alert alert-danger" role="alert">
                <i class="fa fa-warning"></i> <strong>Grandfathered time remaining has been exceeded.</strong>
            </div>
        </div>

        <button type="button" class="btn btn-form-primary btn-lg submitTimeOffRequest">Submit Request</button>
        <br style="clear:both;"/>
        <br style="clear:both;"/>
    </div>
    </div>
    ***/ ?>
</form>