<div class="tab-pane" id="tab-demo5">
    <div class="col-md-1 col-lg-1 moveDown">
        <strong>For:</strong>
    </div>
    <div class="col-md-9 col-lg-8">
        <div class="btn-group col-md-12 col-lg-12">
            <div class="s2-event-log">
                <ul class="js-event-log"></ul>
            </div>

            <select id="requestFor" class="requestFor form-control">
            </select><span class="categoryCloseIcon requestIsForMe glyphicon glyphicon-remove-circle red"></span> 
        </div>
    </div>
    <div class="col-md-2 col-lg-3">
    </div>
</div>
<br style="clear:both;" />
<br style="clear:both;" />
<br style="clear:both;" />