<div class="tab-pane" id="tab-demo5">
    <div class="col-md-1 col-lg-1 moveDown">
        <strong>For:</strong>
    </div>
    <div class="col-md-8 col-lg-8">
        <div class="s2-event-log">
            <ul class="js-event-log"></ul>
        </div>

        <select id="requestFor" class="requestFor form-control">
        </select><span class="categoryCloseIcon requestIsForMe glyphicon glyphicon-remove-circle red">
    </div>
    <div class="col-md-3 col-lg-3">
    </div>
</div>

<br style="clear:both;" />
<br style="clear:both;" />

<div class="tab-pane">
    <div class="col-md-1 col-lg-1 moveDown">
        <strong>Schedule:</strong>
    </div>
    <div class="col-md-8 col-lg-8">
        <div style="float:left;">

            <?php echo $this->partial( 'request/partials/employeeScheduleWidget.phtml' ); ?>

        </div>
        <div style="float:left;padding-left:10px;">
            <button type="button" class="btn btn-form-primary btn-xs toggleLegend launchDialogEditEmployeeSchedule">Edit</button>
        </div>
    </div>
    <div class="col-md-3 col-lg-3">
    </div>
</div>

<br style="clear:both;" />
<br style="clear:both;" />