<form id="newTimeOffRequestForm">
    <div class="row gutter-10 requestWrapper">
        <div class="col-md-3 col-lg-3">

        </div>
        <div class="col-md-6 col-lg-6">
            <div id="datesSelectedDetails">

            </div>

            <input type="hidden" name="formDirty" id="formDirty" value="false" />

            <br style="clear:both;"/>

            <div id="warnFirstDateRequestedTooOld">
                <div class="alert alert-danger bold" role="alert">
                    <i class="fa fa-warning"></i> First date of request is 14 or more days old. Payroll will review this request.
                </div>
            </div>
            
            <div id="warnExceededGrandfatheredHours">
                <div class="alert alert-danger bold" role="alert">
                    <i class="fa fa-warning"></i> You have exceeded the number of Grandfathered hours remaining. Please make the needed adjustments to your request.
                </div>
            </div>
            
            <div id="warnExceededSickHours">
                <div class="alert alert-danger bold" role="alert">
                    <i class="fa fa-warning"></i> You have exceeded the number of Sick hours remaining. Please make the needed adjustments to your request.
                </div>
            </div>

            <div id="warnBereavementDaysPerRequest">
                <div class="alert alert-danger bold" role="alert">
                    <i class="fa fa-warning"></i> A maximum of 3 days of Bereavement are allowed per request.
                </div>
            </div>

			<div id="warnSalaryHoursRequestedMatchSchedule">
                <div class="alert alert-danger bold" role="alert">
                    <i class="fa fa-warning"></i> Salaried employees must take off hours equal to their schedule for each day requested.
                </div>
            </div>

            <div id="warnSalaryTakingRequiredHoursPerDay">
                <div class="alert alert-danger bold" role="alert">
                    <i class="fa fa-warning"></i> Salaried employees must take between 8-12 hours off for each day requested.
                </div>
            </div>

            <div id="warnHourlyTakingRequiredHoursPerDay">
                <div class="alert alert-danger bold" role="alert">
                    <i class="fa fa-warning"></i> Hourly employees must take between 0-12 hours off for each day requested.
                </div>
            </div>

            <div id="requestSubmitDetails">
                <strong>Reason for request:</strong>
                <br style="clear:both;"/>
                <br style="clear:both;"/>
                <textarea style="width:100%;" rows="4" id="requestReason"></textarea>
                <br style="clear:both;"/>
                <br style="clear:both;"/>

                <div id="warnExceededPTOHours">
                    <div class="alert alert-danger bold" role="alert">
                        <i class="fa fa-warning"></i> PTO time remaining has been exceeded. Payroll will review this request.
                    </div>
                </div>

                <div id="warnExceededFloatHours">
                    <div class="alert alert-danger bold" role="alert">
                        <i class="fa fa-warning"></i> Float time remaining has been exceeded. Payroll will review this request.
                    </div>
                </div>

                <div id="warnSick">
                    <div class="alert alert-danger bold" role="alert">
                        <i class="fa fa-warning"></i> Sick time remaining has been exceeded. Payroll will review this request.
                    </div>
                </div>

                <div id="warnGF">
                    <div class="alert alert-danger bold" role="alert">
                        <i class="fa fa-warning"></i> Grandfathered time remaining has been exceeded. Payroll will review this request.
                    </div>
                </div>

                <button type="button" class="btn btn-form-primary btn-lg submitTimeOffRequest">Submit Request</button>
                <br style="clear:both;"/>
                <br style="clear:both;"/>
            </div>
        </div>
        <div class="col-md-3 col-lg-3">

        </div>
    </div>
</form>