<div class="row gutter-10 requestWrapper">
    <div class="col-md-4">

    </div>
    <div class="col-md-4">
        <div id="datesSelectedDetails" style="display:none;">
            
        </div>
        <div id="requestSubmitDetails" style="display:none;">
            <br style="clear:both;"/>
            <strong>Reason for request:</strong>
            <br style="clear:both;"/>
            <br style="clear:both;"/>
            <textarea cols="40" rows="4" id="requestReason"></textarea>
            <br style="clear:both;"/>
            <br style="clear:both;"/>
            
            <div id="warnPTO" style="display:none;">
            	<div class="alert alert-danger" role="alert">
                    <i class="fa fa-warning"></i> <strong>PTO time remaining has been exceeded.</strong>
                </div>
            </div>
            
            <div id="warnFloat" style="display:none;">
            	<div class="alert alert-danger" role="alert">
                    <i class="fa fa-warning"></i> <strong>Float time remaining has been exceeded.</strong>
                </div>
            </div>
            
            <div id="warnSick" style="display:none;">
            	<div class="alert alert-danger" role="alert">
                    <i class="fa fa-warning"></i> <strong>PTO time remaining has been exceeded.</strong>
                </div>
            </div>
            
            <div id="warnGF" style="display:none;">
            	<div class="alert alert-danger" role="alert">
                    <i class="fa fa-warning"></i> <strong>Grandfathered time remaining has been exceeded.</strong>
                </div>
            </div>
            
            <button type="button" class="btn btn-form-primary btn-lg submitTimeOffRequest">Submit Request</button>
            <br style="clear:both;"/>
            <br style="clear:both;"/>
        </div>
    </div>
    <div class="col-md-4">

    </div>
</div>