<form id="newTimeOffRequestForm">
    <div class="row gutter-10 requestWrapper">
        <div class="col-md-3 col-lg-3">

        </div>
        <div class="col-md-6 col-lg-6">
            <div id="datesSelectedDetails" style="display:none;">

            </div>
            
            <input type="hidden" name="formDirty" id="formDirty" value="false" />
            
            <br style="clear:both;"/>
            
            <div id="warnFirstDateRequestedTooOld" style="display:none;">
                <div class="alert alert-danger" role="alert">
                    <i class="fa fa-warning"></i> <strong>First date of request is 14 or more days old. Payroll will review this request.</strong>
                </div>
            </div>
            
            <div id="warnBereavementHoursPerRequest" style="display:none;">
                <div class="alert alert-danger" role="alert">
                    <i class="fa fa-warning"></i> <strong>A maximum of 24 hours of Bereavement are allowed per request.</strong>
                </div>
            </div>
            
            <div id="warnSalaryTakingRequiredHoursPerDay" style="display:none;">
                <div class="alert alert-danger" role="alert">
                    <i class="fa fa-warning"></i> <strong>Salaried employees must take 8 hours off for each day requested.</strong>
                </div>
            </div>
            
            <div id="warnHourlyTakingRequiredHoursPerDay" style="display:none;">
                <div class="alert alert-danger" role="alert">
                    <i class="fa fa-warning"></i> <strong>Hourly employees must take between 0-12 hours off for each day requested.</strong>
                </div>
            </div>
            
            <div id="requestSubmitDetails" style="display:none;">
                <strong>Reason for request:</strong>
                <br style="clear:both;"/>
                <br style="clear:both;"/>
                <textarea style="width:100%;" rows="4" id="requestReason"></textarea>
                <br style="clear:both;"/>
                <br style="clear:both;"/>

                <div id="warnPTO" style="display:none;">
                    <div class="alert alert-danger" role="alert">
                        <i class="fa fa-warning"></i> <strong>PTO time remaining has been exceeded. Payroll will review this request.</strong>
                    </div>
                </div>

                <div id="warnFloat" style="display:none;">
                    <div class="alert alert-danger" role="alert">
                        <i class="fa fa-warning"></i> <strong>Float time remaining has been exceeded. Payroll will review this request.</strong>
                    </div>
                </div>

                <div id="warnSick" style="display:none;">
                    <div class="alert alert-danger" role="alert">
                        <i class="fa fa-warning"></i> <strong>Sick time remaining has been exceeded. Payroll will review this request.</strong>
                    </div>
                </div>

                <div id="warnGF" style="display:none;">
                    <div class="alert alert-danger" role="alert">
                        <i class="fa fa-warning"></i> <strong>Grandfathered time remaining has been exceeded. Payroll will review this request.</strong>
                    </div>
                </div>

                <button type="button" class="btn btn-form-primary btn-lg submitTimeOffRequest">Submit Request</button>
                <br style="clear:both;"/>
                <br style="clear:both;"/>
            </div>
        </div>
        <div class="col-md-3 col-lg-3">

        </div>
    </div>
</form>