<div class="tab-pane" id="tab-demo5">
    <div class="col-md-1 col-lg-1 moveDown">
        <strong>For:</strong>
    </div>
    <div class="col-md-8 col-lg-8">
        <div class="s2-event-log">
            <ul class="js-event-log"></ul>
        </div>

        <select id="requestFor" class="requestFor form-control">
        </select><span class="categoryCloseIcon requestIsForMe glyphicon glyphicon-remove-circle red"></span>
    </div>
    <div class="col-md-3 col-lg-3">
    </div>
</div>

<br style="clear:both;" />
<br style="clear:both;" />

<div class="tab-pane">
    <div class="col-md-1 col-lg-1 moveDown">
        <strong>Schedule:</strong>
    </div>
    <div class="col-md-8 col-lg-8">
        <div style="float:left;">
            <table class="employeeSchedule">
                <thead>
                    <tr>
                        <th>SUN</th>
                        <th>MON</th>
                        <th>TUE</th>
                        <th>WED</th>
                        <th>THU</th>
                        <th>FRI</th>
                        <th>SAT</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td id="scheduleSUN"></td>
                        <td id="scheduleMON"></td>
                        <td id="scheduleTUE"></td>
                        <td id="scheduleWED"></td>
                        <td id="scheduleTHU"></td>
                        <td id="scheduleFRI"></td>
                        <td id="scheduleSAT"></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div style="float:left;padding-left:10px;">
            <a href="#" class="launchDialogEditEmployeeSchedule">Edit</a>
        </div>
    </div>
    <div class="col-md-3 col-lg-3">
    </div>
</div>

<br style="clear:both;" />
<br style="clear:both;" />