<div id="MyWizard" class="wizard">
    <ul class="steps">
        <li data-target="#step1" class="step1 active"><span class="badge badge-info">1</span>Select a Category<span class="chevron"></span></li>
        <li data-target="#step2" class="step2"><span class="badge">2</span>Select date(s)<span class="chevron"></span></li>
        <li data-target="#step3" class="step3 last"><span class="badge">3</span>Provide a Reason & Submit</li>
    </ul>
</div>