<?php
                /**
                 * First output manager warning of stale, unapproved requests.
                 * We don't want them to close this message or have it auto close.
                 **/
                if( ( $this->isManager || $this->isSupervisor ) && $this->countStaleManagerRequests > 0 ) {
                    ?>
                    <div id="applicationStaleManagerRequestsFlashMessage" class="alert alert-danger" role="alert">
                        <i class="fa fa-warning"></i> <strong>You have at least 1 request that is 3 or more days old.</strong><br />
                        Please go to the <a href="<?php echo $this->basepath(); ?>/request/view-manager-queue/pending-manager-approval">Pending Manager Approval</a> queue, then
                        Approve or Deny all requests where the First Day Requested is highlighted in red.
                    </div>
                    <?php
                }

                /** Output any other flash messages * */
                $children = $this->viewModel()->getCurrent()->getChildren();
                $ourView = $children[0];

                if ( isset( $ourView->flashMessages ) && count( $ourView->flashMessages ) ) {
                    foreach ( $ourView->flashMessages as $alertType => $messages ) {
                        if ( !empty( $messages ) ) {
                            switch ( $alertType ) {
                                case 'success':
                                default:
                                    $alertIcon = 'check-square-o';
                                    break;
                            
                                case 'info':
                                    $alertIcon = 'info-circle';
                                    break;
                            
                                case 'warning':
                                case 'danger':
                                    $alertIcon = 'exclamation-circle';
                                    break;
                            }
                            ?>
                            <div id="applicationFlashMessage" class="alert alert-<?php echo $alertType; ?>" role="alert">
                                <button type="button" class="close" data-dismiss="alert">&times;</button>
                                <i class="fa fa-<?php echo $alertIcon; ?>"></i> <strong><?php foreach ( $messages as $mk => $message ) {
                    echo $message . '<br />';
                } ?></strong><br />
                                <div class="autoCloseMessage">This message will auto close in <span class="autoCloseMessage">10</span> seconds.</div>
                            </div>
                            <?php
                        }
                    }
                }
                ?>
