<li><a href="<?php echo $this->basepath(); ?>/request/view-payroll-queue/by-status">By Status</a></li>
<li><a href="<?php echo $this->basepath(); ?>/request/view-payroll-queue/completed-pafs">Completed PAFs</a></li>
<li><a href="<?php echo $this->basepath(); ?>/request/view-payroll-queue/denied">Denied PAFs</a></li>
<li><a href="<?php echo $this->basepath(); ?>/request/view-payroll-queue/manager-action">Manager Action Required</a></li>
<li><a href="<?php echo $this->basepath(); ?>/request/view-payroll-queue/pending-as400-upload">Pending AS400 Upload</a></li>
<li><a href="<?php echo $this->basepath(); ?>/request/view-payroll-queue/pending-payroll-approval">Pending Payroll Approval</a></li>
<li><a href="<?php echo $this->basepath(); ?>/request/view-payroll-queue/update-checks">Update Checks</a></li>
