<li><a href="<?php echo $this->basepath(); ?>/request/manage-payroll-admins">Manage Payroll Admins</a></li>
<li><a href="<?php echo $this->basepath(); ?>/request/manage-payroll-assistants">Manage Payroll Assistants</a></li>
<li><a href="<?php echo $this->basepath(); ?>/request/manage-company-holidays">Manage Company Holidays</a></li>
<?php if ( isset( $_SESSION['Timeoff_' . ENVIRONMENT] ) && ( ENVIRONMENT=='testing' || ENVIRONMENT=='development' ) ) { ?>
	<li><a href="<?php echo $this->basepath(); ?>/request/manage-email-overrides">Manage Email Overrides</a></li>
<?php } ?>