<?php $this->headScript()
                    ->appendFile( $this->basePath( 'templates/swiftit/js/parsley.min.js' ) )
                    ->appendFile( $this->basePath( 'templates/swiftit/js/parsley.remote.min.js' ) )
                    ->appendFile( $this->basePath( 'templates/swiftit/js/bootstrap.min.js' ) )
                    ->appendFile( $this->basePath( 'js/jqueryui/jquery-ui.js' ) )
                    ->appendFile( $this->basePath( 'js/request/timeOffCommon.js' ) )
                    ->appendFile( $this->basePath( 'js/moment/moment.min.js' ) );