<div class="row">
<?php
    $this->searchForm->setAttribute('action', $this->basepath() . '/lettermonitor/retrieve');
    $this->searchForm->prepare();
    echo $this->form()->openTag($this->searchForm)
       . $this->formText($this->searchForm->get('groupnumber')) . '<br>'
       . $this->formSubmit($this->searchForm->get('searchsubmit'))
       . $this->form()->closeTag();
?>
</div>
<div class="row">
<?php

    if ($this->paginator->getTotalItemCount()) { ?>
        <table><tr><th>LMGRP</th><th>LMSEC</th><th>LMID</th><th>LMPART</th><th>LML1DT</th><th>LML2DT</th><th>LML3DT</th><th>LMRDT</th><th>LMSDT</th></tr>
        <?php
        foreach ($this->paginator as $letterSent) {
            echo '<tr style="background-color:'
                . $this->cycle(array('#F0F0F0', '#FFFFFF'))->next()
                . '">';
            foreach ($letterSent as $column) {
                echo '<td>' . $this->escapehtml(trim($column)) . '</td>';
            }
            echo '</tr>';
        }

        echo '</table>';
    }

echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'pagination_control', array('route' => 'lettermonitor'));
// fix route above
?>
</div>

<div class="span5">
        <h2><?php echo $this->translate('Letter Monitor Maintenance') ?></h2>
        <p><?php echo 'Put some explanatory text here...' ?></p>
        <ol>
            <li>Create/Add a new Letter Monitor</li>
            <li>Retrieve/View a detail record</li>
            <li>Update/Edit a Letter Monitor</li>
            <li>Delete/Remove a Letter Monitor</li>
        </ol>
    </div>
</div>
